INSERT INTO user_register (id, fullname, dob, maritalstatus, gender, fathername, mothername, country, state, city, addresstype, resadd, workadd, mothertongue, nationality, religion, caste, subcaste, castedes, height, weight, bodytype, complexion, phystatus, motherlaw, email, higeducation, emptype, income, companyname, designation, annualincome, star, rassi, dhosham, food, birthtime, familystatus, familytype, Parentsnum, Parentsnum2, parentsincome, description, sibilingsone, sibilingageone, sibilingtypeone, sibilingtwo, sibilingagetwo, sibilingtypetwo, profileone, profiletwo, profilethree, familyprofileone, familyprofiletwo, horoscope)
VALUES
    (16, 'John Doe', '1990-05-15', 'Single', 'Male', 'John Doe Sr.', 'Jane Doe', 'USA', 'California', 'Los Angeles', 'Residential', '123 Main St', '456 Work St', 'English', 'American', 'Christian', 'Caste', 'Subcaste', 'Caste Description', 180, 70, 'Average', 'Fair', 'Good', 'Mother-in-Law', 'john.doe@example.com', 'Masters', 'Full-time', 50000, 'ABC Company', 'Manager', 60000, 'Leo', 'Virgo', 'No Dosham', 'Non-Vegetarian', '10:00 AM', 'Middle class', 'Nuclear', 2, 2, 50000, 'Description', 'Sister', '25', 'Married', 'Brother', '30', 'Unmarried', 'Profile1.jpg', 'Profile2.jpg', 'Profile3.jpg', 'FamilyProfile1.jpg', 'FamilyProfile2.jpg', 'Horoscope.jpg');

INSERT INTO user_register (id, fullname, dob, maritalstatus, gender, fathername, mothername, country, state, city, addresstype, resadd, workadd, mothertongue, nationality, religion, caste, subcaste, castedes, height, weight, bodytype, complexion, phystatus, motherlaw, email, higeducation, emptype, income, companyname, designation, annualincome, star, rassi, dhosham, food, birthtime, familystatus, familytype, Parentsnum, Parentsnum2, parentsincome, description, sibilingsone, sibilingageone, sibilingtypeone, sibilingtwo, sibilingagetwo, sibilingtypetwo, profileone, profiletwo, profilethree, familyprofileone, familyprofiletwo, horoscope)
VALUES
    (17, 'John Doe', '1990-05-15', 'Single', 'Male', 'John Doe Sr.', 'Jane Doe', 'USA', 'California', 'Los Angeles', 'Residential', '123 Main St', '456 Work St', 'English', 'American', 'Christian', 'Caste', 'Subcaste', 'Caste Description', 180, 70, 'Average', 'Fair', 'Good', 'Mother-in-Law', 'john.doe@example.com', 'Masters', 'Full-time', 50000, 'ABC Company', 'Manager', 60000, 'Leo', 'Virgo', 'No Dosham', 'Non-Vegetarian', '10:00 AM', 'Middle class', 'Nuclear', 2, 2, 50000, 'Description', 'Sister', '25', 'Married', 'Brother', '30', 'Unmarried', 'Profile1.jpg', 'Profile2.jpg', 'Profile3.jpg', 'FamilyProfile1.jpg', 'FamilyProfile2.jpg', 'Horoscope.jpg');

INSERT INTO user_register (id, fullname, dob, maritalstatus, gender, fathername, mothername, country, state, city, addresstype, resadd, workadd, mothertongue, nationality, religion, caste, subcaste, castedes, height, weight, bodytype, complexion, phystatus, motherlaw, email, higeducation, emptype, income, companyname, designation, annualincome, star, rassi, dhosham, food, birthtime, familystatus, familytype, Parentsnum, Parentsnum2, parentsincome, description, sibilingsone, sibilingageone, sibilingtypeone, sibilingtwo, sibilingagetwo, sibilingtypetwo, profileone, profiletwo, profilethree, familyprofileone, familyprofiletwo, horoscope)
VALUES
    (18, 'John Doe', '1990-05-15', 'Single', 'Male', 'John Doe Sr.', 'Jane Doe', 'USA', 'California', 'Los Angeles', 'Residential', '123 Main St', '456 Work St', 'English', 'American', 'Christian', 'Caste', 'Subcaste', 'Caste Description', 180, 70, 'Average', 'Fair', 'Good', 'Mother-in-Law', 'john.doe@example.com', 'Masters', 'Full-time', 50000, 'ABC Company', 'Manager', 60000, 'Leo', 'Virgo', 'No Dosham', 'Non-Vegetarian', '10:00 AM', 'Middle class', 'Nuclear', 2, 2, 50000, 'Description', 'Sister', '25', 'Married', 'Brother', '30', 'Unmarried', 'Profile1.jpg', 'Profile2.jpg', 'Profile3.jpg', 'FamilyProfile1.jpg', 'FamilyProfile2.jpg', 'Horoscope.jpg');


INSERT INTO user_register (id, fullname, dob, maritalstatus, gender, fathername, mothername, country, state, city, addresstype, resadd, workadd, mothertongue, nationality, religion, caste, subcaste, castedes, height, weight, bodytype, complexion, phystatus, motherlaw, email, higeducation, emptype, income, companyname, designation, annualincome, star, rassi, dhosham, food, birthtime, familystatus, familytype, Parentsnum, Parentsnum2, parentsincome, description, sibilingsone, sibilingageone, sibilingtypeone, sibilingtwo, sibilingagetwo, sibilingtypetwo, profileone, profiletwo, profilethree, familyprofileone, familyprofiletwo, horoscope)
VALUES
    (19, 'John Doe', '1990-05-15', 'Single', 'Male', 'John Doe Sr.', 'Jane Doe', 'USA', 'California', 'Los Angeles', 'Residential', '123 Main St', '456 Work St', 'English', 'American', 'Christian', 'Caste', 'Subcaste', 'Caste Description', 180, 70, 'Average', 'Fair', 'Good', 'Mother-in-Law', 'john.doe@example.com', 'Masters', 'Full-time', 50000, 'ABC Company', 'Manager', 60000, 'Leo', 'Virgo', 'No Dosham', 'Non-Vegetarian', '10:00 AM', 'Middle class', 'Nuclear', 2, 2, 50000, 'Description', 'Sister', '25', 'Married', 'Brother', '30', 'Unmarried', 'Profile1.jpg', 'Profile2.jpg', 'Profile3.jpg', 'FamilyProfile1.jpg', 'FamilyProfile2.jpg', 'Horoscope.jpg');


INSERT INTO user_register (id, fullname, dob, maritalstatus, gender, fathername, mothername, country, state, city, addresstype, resadd, workadd, mothertongue, nationality, religion, caste, subcaste, castedes, height, weight, bodytype, complexion, phystatus, motherlaw, email, higeducation, emptype, income, companyname, designation, annualincome, star, rassi, dhosham, food, birthtime, familystatus, familytype, Parentsnum, Parentsnum2, parentsincome, description, sibilingsone, sibilingageone, sibilingtypeone, sibilingtwo, sibilingagetwo, sibilingtypetwo, profileone, profiletwo, profilethree, familyprofileone, familyprofiletwo, horoscope)
VALUES
    (20, 'John Doe', '1990-05-15', 'Single', 'Male', 'John Doe Sr.', 'Jane Doe', 'USA', 'California', 'Los Angeles', 'Residential', '123 Main St', '456 Work St', 'English', 'American', 'Christian', 'Caste', 'Subcaste', 'Caste Description', 180, 70, 'Average', 'Fair', 'Good', 'Mother-in-Law', 'john.doe@example.com', 'Masters', 'Full-time', 50000, 'ABC Company', 'Manager', 60000, 'Leo', 'Virgo', 'No Dosham', 'Non-Vegetarian', '10:00 AM', 'Middle class', 'Nuclear', 2, 2, 50000, 'Description', 'Sister', '25', 'Married', 'Brother', '30', 'Unmarried', 'Profile1.jpg', 'Profile2.jpg', 'Profile3.jpg', 'FamilyProfile1.jpg', 'FamilyProfile2.jpg', 'Horoscope.jpg');

